/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "PearlThrough"
includeBuild("platforms")
includeBuild("build-logic")
includeBuild("api")
includeBuild("nms")
includeBuild("plugin")
